export { Lamp } from "./lamps";
export { Retro } from "./retros";
export { Special } from "./specials";
export { Electronic } from "./electronics";
export { News } from "./news";
export { Testimonial } from "./testimonials";
export { Histroy } from "./history";
export { Support } from "./support";
export { Partner } from "./partner";
